site_name: Pragmatic Dev Snippets
site_url: https://lalver1.github.io/coding-notes
repo_url: https://github.com/lalver1/coding-notes

theme:
  name: material
  features:
    - navigation.sections
    - navigation.path

markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Version Control:
    - Git: version-control/git.md
    - GitHub: version-control/github.md
  - Docker:
    - Build: docker/build.md
    - Compose: docker/compose.md

